[package]
name = "reactive"
version = "0.1.0"
authors = ["cyber-meow <sjungle305@gmail.com>"]

[dependencies]
either = "1.3"
crossbeam = "0.3.0"
rand = "0.3"
ordermap = "0.3.2"

[features]
debug = []
abort_if_panic = []
